[package]
name = "actix-api"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
serde = { version = "1.0.219", features = ["derive"] }
dotenv = "0.15.0"
sqlx = { version = "0.8.3", features = ["runtime-async-std-native-tls", "postgres"] }
serde_json = "1.0.140"
